
################################################################
#
# VIEW çÏê¨
#
################################################################



CREATE VIEW  v_staff ( staff_id, user_id, staff_name, password ) AS SELECT m_staff.staff_id, m_staff.user_id, m_staff.staff_name, m_staff.password FROM saikyo.m_staff;
CREATE VIEW  v_routine_exam ( pupil_enroll_id, routine_exam_subject_id, score ) AS SELECT t_routine_exam.pupil_enroll_id, t_routine_exam.routine_exam_subject_id, t_routine_exam.score FROM t_routine_exam;
CREATE VIEW  v_mock_exam ( pupil_enroll_id, mock_exam_id, mock_exam_subject_id, score, deviation_value, place, choice_school_name, choice_school_judgement ) AS SELECT t_mock_exam.pupil_enroll_id, t_mock_exam.mock_exam_id, t_mock_exam.mock_exam_subject_id, t_mock_exam.score, t_mock_exam.deviation_value, t_mock_exam.place, t_mock_exam.choice_school_name, t_mock_exam.choice_school_judgement FROM t_mock_exam;
CREATE VIEW  v_report_card_subject_valuation ( pupil_enroll_id, term, report_card_subject_viewpoint_id, valuation_code ) AS SELECT t_report_card_subject_valuation.pupil_enroll_id, t_report_card_subject_valuation.term, t_report_card_subject_valuation.report_card_subject_viewpoint_id, t_report_card_subject_valuation.valuation_code FROM t_report_card_subject_valuation;
CREATE VIEW  v_report_card_rating ( pupil_enroll_id, term, report_card_subject_id, rating_code, year_rating_code ) AS SELECT t_report_card_rating.pupil_enroll_id, t_report_card_rating.term, t_report_card_rating.report_card_subject_id, t_report_card_rating.rating_code, t_report_card_rating.year_rating_code FROM t_report_card_rating;
CREATE VIEW  v_report_card_behavior_state_valuation ( pupil_enroll_id, term, report_card_behavior_state_id, valuation_code ) AS SELECT t_report_card_behavior_state_valuation.pupil_enroll_id, t_report_card_behavior_state_valuation.term, t_report_card_behavior_state_valuation.report_card_behavior_state_id, t_report_card_behavior_state_valuation.valuation_code FROM t_report_card_behavior_state_valuation;
CREATE VIEW  v_report_card_subject_opinion ( pupil_enroll_id, term, report_card_subject_id, opinion ) AS SELECT t_report_card_subject_opinion.pupil_enroll_id, t_report_card_subject_opinion.term, t_report_card_subject_opinion.report_card_subject_id, t_report_card_subject_opinion.opinion FROM t_report_card_subject_opinion;
CREATE VIEW  v_report_card_opinion ( pupil_enroll_id, term, report_card_opinion_id, opinion ) AS SELECT t_report_card_opinion.pupil_enroll_id, t_report_card_opinion.term, t_report_card_opinion.report_card_opinion_id, t_report_card_opinion.opinion FROM t_report_card_opinion;
CREATE VIEW  v_guidance_record_subject_valuation ( pupil_enroll_id, school_year, guidance_record_subject_viewpoint_id, valuation_code ) AS SELECT t_guidance_record_subject_valuation.pupil_enroll_id, t_guidance_record_subject_valuation.school_year, t_guidance_record_subject_valuation.guidance_record_subject_viewpoint_id, t_guidance_record_subject_valuation.valuation_code FROM t_guidance_record_subject_valuation;
CREATE VIEW  v_guidance_record_rating ( pupil_enroll_id, school_year, guidance_record_subject_id, rating_code ) AS SELECT t_guidance_record_rating.pupil_enroll_id, t_guidance_record_rating.school_year, t_guidance_record_rating.guidance_record_subject_id, t_guidance_record_rating.rating_code FROM t_guidance_record_rating;
CREATE VIEW  v_guidance_record_behavior_valuation ( pupil_enroll_id, school_year, guidance_record_behavior_id, assessment ) AS SELECT t_guidance_record_behavior_valuation.pupil_enroll_id, t_guidance_record_behavior_valuation.school_year, t_guidance_record_behavior_valuation.guidance_record_behavior_id, t_guidance_record_behavior_valuation.assessment FROM t_guidance_record_behavior_valuation;
CREATE VIEW  v_guidance_record_special_activity_viewpoint ( pupil_enroll_id, school_year, guidance_record_id, viewpoint_detail ) AS SELECT t_guidance_record_special_activity_viewpoint.pupil_enroll_id, t_guidance_record_special_activity_viewpoint.school_year, t_guidance_record_special_activity_viewpoint.guidance_record_id, t_guidance_record_special_activity_viewpoint.viewpoint_detail FROM t_guidance_record_special_activity_viewpoint;
CREATE VIEW  v_guidance_record_special_activity_valuation ( pupil_enroll_id, school_year, guidance_record_special_activity_id, assessment ) AS SELECT t_guidance_record_special_activity_valuation.pupil_enroll_id, t_guidance_record_special_activity_valuation.school_year, t_guidance_record_special_activity_valuation.guidance_record_special_activity_id, t_guidance_record_special_activity_valuation.assessment FROM t_guidance_record_special_activity_valuation;
CREATE VIEW  v_guidance_record_integrated_studies_valuation ( pupil_enroll_id, school_year, guidance_record_integrated_studies_id, detail ) AS SELECT t_guidance_record_integrated_studies_valuation.pupil_enroll_id, t_guidance_record_integrated_studies_valuation.school_year, t_guidance_record_integrated_studies_valuation.guidance_record_integrated_studies_id, t_guidance_record_integrated_studies_valuation.detail FROM t_guidance_record_integrated_studies_valuation;
CREATE VIEW  v_guidance_record_opinion ( pupil_enroll_id, school_year, guidance_record_opinion_id, opinion ) AS SELECT t_guidance_record_opinion.pupil_enroll_id, t_guidance_record_opinion.school_year, t_guidance_record_opinion.guidance_record_opinion_id, t_guidance_record_opinion.opinion FROM t_guidance_record_opinion;
CREATE VIEW  v_class_date ( school_year, term, integrated_grade_code , class_date ) AS SELECT t_class_date.school_year, t_class_date.term, t_class_date.integrated_grade_code, t_class_date.class_date FROM t_class_date;
CREATE VIEW  v_attendance_record ( pupil_enroll_id, date, absence_reason_id ) AS SELECT t_attendance_record.pupil_enroll_id, t_attendance_record.date, t_attendance_record.absence_reason_id FROM t_attendance_record;
CREATE VIEW  v_report_card_subject_viewpoint ( report_card_subject_viewpoint_id, school_year, term, report_card_subject_id, serial_num, display_no, viewpoint ) AS SELECT m_report_card_subject_viewpoint.report_card_subject_viewpoint_id, m_report_card_subject_viewpoint.school_year, m_report_card_subject_viewpoint.term, m_report_card_subject_viewpoint.report_card_subject_id, m_report_card_subject_viewpoint.serial_num, m_report_card_subject_viewpoint.display_no, m_report_card_subject_viewpoint.viewpoint FROM m_report_card_subject_viewpoint;
CREATE VIEW  v_report_card_behavior_state ( report_card_behavior_state_id, school_year, term, report_card_id, serial_num, display_no, valuation_detail ) AS SELECT m_report_card_behavior_state.report_card_behavior_state_id, m_report_card_behavior_state.school_year, m_report_card_behavior_state.term, m_report_card_behavior_state.report_card_id, m_report_card_behavior_state.serial_num, m_report_card_behavior_state.display_no, m_report_card_behavior_state.valuation_detail FROM m_report_card_behavior_state;
CREATE VIEW  v_routine_exam_subject ( routine_exam_subject_id, routine_exam_id, integrated_grade_code , serial_num, subject_id, display_no ) AS SELECT m_routine_exam_subject.routine_exam_subject_id, m_routine_exam_subject.routine_exam_id, m_routine_exam_subject.subject_id, m_routine_exam_subject.integrated_grade_code , m_routine_exam_subject.serial_num, m_routine_exam_subject.display_no FROM m_routine_exam_subject;
CREATE VIEW  v_mock_exam_master ( mock_exam_id, school_year, serial_num, mock_exam_date, mock_exam_name, mock_exam_abv ) AS SELECT m_mock_exam.mock_exam_id, m_mock_exam.school_year, m_mock_exam.serial_num, m_mock_exam.mock_exam_date, m_mock_exam.mock_exam_name, m_mock_exam.mock_exam_abv FROM m_mock_exam;
CREATE VIEW  v_mock_exam_average ( mock_exam_average_id, mock_exam_id, mock_exam_subject_id, integrated_grade_code , serial_num, average_score ) AS SELECT m_mock_exam_average.mock_exam_average_id, m_mock_exam_average.mock_exam_id, m_mock_exam_average.mock_exam_subject_id, m_mock_exam_average.integrated_grade_code , m_mock_exam_average.serial_num, m_mock_exam_average.average_score FROM m_mock_exam_average;

