----------------------------------------
-- t_pupils_basic
-- 2013/8/8 new create@yoshida
-- 2016/6/28    update@yoshida
----------------------------------------
CREATE TABLE `t_pupils_basic` (
  `pupil_id` int(11) NOT NULL,
  `pupil_card_num` varchar(10) NOT NULL,
  `name_last` varchar(255) DEFAULT NULL,
  `name_first` varchar(255) DEFAULT NULL,
  `kana_last` varchar(255) DEFAULT NULL,
  `kana_first` varchar(255) DEFAULT NULL,
  `sex_code` int(11) NOT NULL,
  `birthday` char(10) DEFAULT NULL,
  `guardian` varchar(255) DEFAULT NULL,
  `family_relationship_code` int(11) DEFAULT NULL,
  `father_name` varchar(255) DEFAULT NULL,
  `mather_name` varchar(255) DEFAULT NULL,
  `sibling_name1` varchar(255) DEFAULT NULL,
  `sibling_birthday1` char(10) DEFAULT NULL,
  `sibling_name2` varchar(255) DEFAULT NULL,
  `sibling_birthday2` char(10) DEFAULT NULL,
  `sibling_name3` varchar(255) DEFAULT NULL,
  `sibling_birthday3` char(10) DEFAULT NULL,
  `firstborn` varchar(255) DEFAULT NULL,
  `district_id` int(11) DEFAULT NULL,
  `zip_no` char(8) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `permanent_domicile` varchar(255) DEFAULT NULL,
  `go_to_school_code_out` int(11) DEFAULT NULL,
  `bus_course_id_out` int(11) DEFAULT NULL,
  `bus_station_out` varchar(255) DEFAULT NULL,
  `train_station_out` varchar(255) DEFAULT NULL,
  `go_to_school_code_in` int(11) DEFAULT NULL,
  `bus_course_id_in` int(11) DEFAULT NULL,
  `bus_station_in` varchar(255) DEFAULT NULL,
  `train_station_in` varchar(255) DEFAULT NULL,
  `commuting_time` varchar(255) DEFAULT NULL,
  `home_tel_no` varchar(255) DEFAULT NULL,
  `fax_no` varchar(255) DEFAULT NULL,
  `mail1` varchar(255) DEFAULT NULL,
  `mail2` varchar(255) DEFAULT NULL,
  `father_mobile_tel_no` varchar(255) DEFAULT NULL,
  `father_work` varchar(255) DEFAULT NULL,
  `father_work_tel_no` varchar(255) DEFAULT NULL,
  `mother_mobile_tel_no` varchar(255) DEFAULT NULL,
  `mother_work` varchar(255) DEFAULT NULL,
  `mother_work_tel_no` varchar(255) DEFAULT NULL,
  `emergency_contact1` varchar(255) DEFAULT NULL,
  `emergency_contact2` varchar(255) DEFAULT NULL,
  `emergency_contact3` varchar(255) DEFAULT NULL,
  `lesson1` varchar(255) DEFAULT NULL,
  `lesson2` varchar(255) DEFAULT NULL,
  `lesson3` varchar(255) DEFAULT NULL,
  `award` varchar(255) DEFAULT NULL,
  `mobile_flg` char(1) NOT NULL,
  `mobile_tel_no` varchar(255) DEFAULT NULL,
  `allergy` varchar(255) DEFAULT NULL,
  `school_lunch_flg` char(1) NOT NULL,
  `milk_flg` char(1) NOT NULL,
  `ent_into_date` char(10) DEFAULT NULL,
  `alma_mater` varchar(255) DEFAULT NULL,
  `remarks_column` varchar(255) DEFAULT NULL,
  `ent_exam_id` int(11) DEFAULT NULL,
  `create_id` int(11) NOT NULL,
  `create_date` datetime NOT NULL DEFAULT '1000-01-01 00:00:00',
  `update_id` int(11) NOT NULL,
  `update_date` datetime NOT NULL DEFAULT '1000-01-01 00:00:00',
  PRIMARY KEY (`pupil_id`),
  UNIQUE KEY (`pupil_card_num`),
  FOREIGN KEY (`sex_code`)
         REFERENCES m_sex_code(`sex_code`),
  FOREIGN KEY (`family_relationship_code`)
         REFERENCES m_family_relationship_code(`family_relationship_code`),
  FOREIGN KEY (`district_id`)
         REFERENCES m_district(`district_id`),
  FOREIGN KEY (`go_to_school_code_out`)
         REFERENCES m_go_to_school_code(`go_to_school_code`),
  FOREIGN KEY (`bus_course_id_out`)
         REFERENCES m_bus_course(`bus_course_id`),
  FOREIGN KEY (`go_to_school_code_in`)
         REFERENCES m_go_to_school_code(`go_to_school_code`),
  FOREIGN KEY (`bus_course_id_in`)
         REFERENCES m_bus_course(`bus_course_id`),
  FOREIGN KEY (`ent_exam_id`)
         REFERENCES t_ent_exam(`ent_exam_id`)
);



CREATE TABLE `t_pupils_basic` (
	`pupil_id` INT(11) NOT NULL,
	`pupil_card_num` VARCHAR(10) NOT NULL,
	`name_last` VARCHAR(40) NULL DEFAULT NULL,
	`name_first` VARCHAR(40) NULL DEFAULT NULL,
	`kana_last` VARCHAR(40) NULL DEFAULT NULL,
	`kana_first` VARCHAR(40) NULL DEFAULT NULL,
	`sex_code` INT(11) NOT NULL,
	`birthday` CHAR(10) NULL DEFAULT NULL,
	`guardian` VARCHAR(255) NULL DEFAULT NULL,
	`family_relationship_code` INT(11) NULL DEFAULT NULL,
	`father_name` VARCHAR(40) NULL DEFAULT NULL,
	`mather_name` VARCHAR(40) NULL DEFAULT NULL,
	`sibling_name1` VARCHAR(40) NULL DEFAULT NULL,
	`sibling_birthday1` CHAR(10) NULL DEFAULT NULL,
	`sibling_name2` VARCHAR(40) NULL DEFAULT NULL,
	`sibling_birthday2` CHAR(10) NULL DEFAULT NULL,
	`sibling_name3` VARCHAR(40) NULL DEFAULT NULL,
	`sibling_birthday3` CHAR(10) NULL DEFAULT NULL,
	`firstborn` VARCHAR(40) NULL DEFAULT NULL,
	`district_id` INT(11) NULL DEFAULT NULL,
	`zip_no` CHAR(8) NULL DEFAULT NULL,
	`address` VARCHAR(255) NULL DEFAULT NULL,
	`permanent_domicile` VARCHAR(40) NULL DEFAULT NULL,
	`go_to_school_code_out` INT(11) NULL DEFAULT NULL,
	`bus_course_id_out` INT(11) NULL DEFAULT NULL,
	`bus_station_out` VARCHAR(40) NULL DEFAULT NULL,
	`train_station_out` VARCHAR(40) NULL DEFAULT NULL,
	`go_to_school_code_in` INT(11) NULL DEFAULT NULL,
	`bus_course_id_in` INT(11) NULL DEFAULT NULL,
	`bus_station_in` VARCHAR(40) NULL DEFAULT NULL,
	`train_station_in` VARCHAR(40) NULL DEFAULT NULL,
	`commuting_time` VARCHAR(40) NULL DEFAULT NULL,
	`home_tel_no` VARCHAR(20) NULL DEFAULT NULL,
	`fax_no` VARCHAR(20) NULL DEFAULT NULL,
	`mail1` VARCHAR(255) NULL DEFAULT NULL,
	`mail2` VARCHAR(255) NULL DEFAULT NULL,
	`father_mobile_tel_no` VARCHAR(20) NULL DEFAULT NULL,
	`father_work` VARCHAR(100) NULL DEFAULT NULL,
	`father_work_tel_no` VARCHAR(20) NULL DEFAULT NULL,
	`mother_mobile_tel_no` VARCHAR(20) NULL DEFAULT NULL,
	`mother_work` VARCHAR(100) NULL DEFAULT NULL,
	`mother_work_tel_no` VARCHAR(20) NULL DEFAULT NULL,
	`emergency_contact1` VARCHAR(20) NULL DEFAULT NULL,
	`emergency_contact2` VARCHAR(20) NULL DEFAULT NULL,
	`emergency_contact3` VARCHAR(20) NULL DEFAULT NULL,
	`lesson1` VARCHAR(255) NULL DEFAULT NULL,
	`lesson2` VARCHAR(255) NULL DEFAULT NULL,
	`lesson3` VARCHAR(255) NULL DEFAULT NULL,
	`award` VARCHAR(500) NULL DEFAULT NULL,
	`mobile_flg` CHAR(1) NOT NULL,
	`mobile_tel_no` VARCHAR(20) NULL DEFAULT NULL,
	`allergy` VARCHAR(255) NULL DEFAULT NULL,
	`school_lunch_flg` CHAR(1) NOT NULL,
	`milk_flg` CHAR(1) NOT NULL,
	`ent_into_date` CHAR(10) NULL DEFAULT NULL,
	`alma_mater` VARCHAR(100) NULL DEFAULT NULL,
	`remarks_column` VARCHAR(255) NULL DEFAULT NULL,
	`ent_exam_id` INT(11) NULL DEFAULT NULL,
	`father_kana` VARCHAR(20) NULL DEFAULT NULL,
	`father_birthday` CHAR(10) NULL DEFAULT NULL,
	`mother_kana` VARCHAR(20) NULL DEFAULT NULL,
	`mother_birthday` CHAR(10) NULL DEFAULT NULL,
	`emergency_contact1_kind_code` INT(11) NULL DEFAULT NULL,
	`emergency_contact1_kind` VARCHAR(10) NULL DEFAULT NULL,
	`emergency_contact2_kind_code` INT(11) NULL DEFAULT NULL,
	`emergency_contact2_kind` VARCHAR(10) NULL DEFAULT NULL,
	`emergency_contact3_kind_code` INT(11) NULL DEFAULT NULL,
	`emergency_contact3_kind` VARCHAR(10) NULL DEFAULT NULL,
	`overseas_residents_departure_date_more_than_a_year` CHAR(8) NULL DEFAULT NULL,
	`overseas_residents_return_date_more_than_a_year` CHAR(8) NULL DEFAULT NULL,
	`overseas_residents_country_more_than_a_year` VARCHAR(20) NULL DEFAULT NULL,
	`overseas_residents_school_name_more_than_a_year` VARCHAR(20) NULL DEFAULT NULL,
	`firstborn_flg` CHAR(1) NULL DEFAULT NULL,
	`family_structure1_name` VARCHAR(20) NULL DEFAULT NULL,
	`family_structure1_birthday` CHAR(10) NULL DEFAULT NULL,
	`family_structure1_relationship_code` INT(11) NULL DEFAULT NULL,
	`family_structure1_Affiliation` VARCHAR(20) NULL DEFAULT NULL,
	`family_structure1_pupil_card_num` VARCHAR(10) NULL DEFAULT NULL,
	`family_structure2_name` VARCHAR(20) NULL DEFAULT NULL,
	`family_structure2_birthday` CHAR(10) NULL DEFAULT NULL,
	`family_structure2_relationship_code` INT(11) NULL DEFAULT NULL,
	`family_structure2_Affiliation` VARCHAR(20) NULL DEFAULT NULL,
	`family_structure2_pupil_card_num` VARCHAR(10) NULL DEFAULT NULL,
	`family_structure3_name` VARCHAR(20) NULL DEFAULT NULL,
	`family_structure3_birthday` CHAR(10) NULL DEFAULT NULL,
	`family_structure3_relationship_code` INT(11) NULL DEFAULT NULL,
	`family_structure3_Affiliation` VARCHAR(20) NULL DEFAULT NULL,
	`family_structure3_pupil_card_num` VARCHAR(10) NULL DEFAULT NULL,
	`family_structure4_name` VARCHAR(20) NULL DEFAULT NULL,
	`family_structure4_birthday` CHAR(10) NULL DEFAULT NULL,
	`family_structure4_relationship_code` INT(11) NULL DEFAULT NULL,
	`family_structure4_Affiliation` VARCHAR(20) NULL DEFAULT NULL,
	`family_structure4_pupil_card_num` VARCHAR(10) NULL DEFAULT NULL,
	`family_structure5_name` VARCHAR(20) NULL DEFAULT NULL,
	`family_structure5_birthday` CHAR(10) NULL DEFAULT NULL,
	`family_structure5_relationship_code` INT(11) NULL DEFAULT NULL,
	`family_structure5_Affiliation` VARCHAR(20) NULL DEFAULT NULL,
	`family_structure5_pupil_card_num` VARCHAR(10) NULL DEFAULT NULL,
	`family_structure6_name` VARCHAR(20) NULL DEFAULT NULL,
	`family_structure6_birthday` CHAR(10) NULL DEFAULT NULL,
	`family_structure6_relationship_code` INT(11) NULL DEFAULT NULL,
	`family_structure6_Affiliation` VARCHAR(20) NULL DEFAULT NULL,
	`family_structure6_pupil_card_num` VARCHAR(10) NULL DEFAULT NULL,
	`family_structure7_name` VARCHAR(20) NULL DEFAULT NULL,
	`family_structure7_birthday` CHAR(10) NULL DEFAULT NULL,
	`family_structure7_relationship_code` INT(11) NULL DEFAULT NULL,
	`family_structure7_Affiliation` VARCHAR(20) NULL DEFAULT NULL,
	`family_structure7_pupil_card_num` VARCHAR(10) NULL DEFAULT NULL,
	`family_structure8_name` VARCHAR(20) NULL DEFAULT NULL,
	`family_structure8_birthday` CHAR(10) NULL DEFAULT NULL,
	`family_structure8_relationship_code` INT(11) NULL DEFAULT NULL,
	`family_structure8_Affiliation` VARCHAR(20) NULL DEFAULT NULL,
	`family_structure8_pupil_card_num` VARCHAR(10) NULL DEFAULT NULL,
	`lesson1_field` VARCHAR(255) NULL DEFAULT NULL,
	`lesson1_place` VARCHAR(255) NULL DEFAULT NULL,
	`lesson1_field_day_of_the_week` VARCHAR(255) NULL DEFAULT NULL,
	`lesson2_field` VARCHAR(20) NULL DEFAULT NULL,
	`lesson2_place` VARCHAR(40) NULL DEFAULT NULL,
	`lesson2_field_day_of_the_week` VARCHAR(15) NULL DEFAULT NULL,
	`lesson3_field` VARCHAR(20) NULL DEFAULT NULL,
	`lesson3_place` VARCHAR(40) NULL DEFAULT NULL,
	`lesson3_field_day_of_the_week` VARCHAR(15) NULL DEFAULT NULL,
	`certificate_kanji` VARCHAR(10) NULL DEFAULT NULL,
	`certificate_kanji_period` CHAR(8) NULL DEFAULT NULL,
	`certificate_math` VARCHAR(10) NULL DEFAULT NULL,
	`certificate_math_period` CHAR(8) NULL DEFAULT NULL,
	`certificate_english` VARCHAR(10) NULL DEFAULT NULL,
	`certificate_english_period` CHAR(8) NULL DEFAULT NULL,
	`certificate_japanese` VARCHAR(10) NULL DEFAULT NULL,
	`certificate_japanese_period` CHAR(8) NULL DEFAULT NULL,
	`certificate_english_jr` VARCHAR(10) NULL DEFAULT NULL,
	`certificate_english_jr_period` CHAR(8) NULL DEFAULT NULL,
	`certificate_etc` VARCHAR(10) NULL DEFAULT NULL,
	`certificate_etc_period` CHAR(8) NULL DEFAULT NULL,
	`go_to_school_code_out_mon` INT(11) NULL DEFAULT NULL,
	`bus_course_id_out_mon` INT(11) NULL DEFAULT NULL,
	`bus_station_out_mon` VARCHAR(20) NULL DEFAULT NULL,
	`train_station_out_mon` VARCHAR(20) NULL DEFAULT NULL,
	`hirata_code_out_mon` INT(11) NULL DEFAULT NULL,
	`commuting_time_out_mon` VARCHAR(10) NULL DEFAULT NULL,
	`go_to_school_code_out_tue` INT(11) NULL DEFAULT NULL,
	`bus_course_id_out_tue` INT(11) NULL DEFAULT NULL,
	`bus_station_out_tue` VARCHAR(20) NULL DEFAULT NULL,
	`train_station_out_tue` VARCHAR(20) NULL DEFAULT NULL,
	`hirata_code_out_tue` INT(11) NULL DEFAULT NULL,
	`commuting_time_out_tue` VARCHAR(10) NULL DEFAULT NULL,
	`go_to_school_code_out_wed` INT(11) NULL DEFAULT NULL,
	`bus_course_id_out_wed` INT(11) NULL DEFAULT NULL,
	`bus_station_out_wed` VARCHAR(20) NULL DEFAULT NULL,
	`train_station_out_wed` VARCHAR(20) NULL DEFAULT NULL,
	`hirata_code_out_wed` INT(11) NULL DEFAULT NULL,
	`commuting_time_out_wed` VARCHAR(10) NULL DEFAULT NULL,
	`go_to_school_code_out_thu` INT(11) NULL DEFAULT NULL,
	`bus_course_id_out_thu` INT(11) NULL DEFAULT NULL,
	`bus_station_out_thu` VARCHAR(20) NULL DEFAULT NULL,
	`train_station_out_thu` VARCHAR(20) NULL DEFAULT NULL,
	`hirata_code_out_thu` INT(11) NULL DEFAULT NULL,
	`commuting_time_out_thu` VARCHAR(10) NULL DEFAULT NULL,
	`go_to_school_code_out_fri` INT(11) NULL DEFAULT NULL,
	`bus_course_id_out_fri` INT(11) NULL DEFAULT NULL,
	`bus_station_out_fri` VARCHAR(20) NULL DEFAULT NULL,
	`train_station_out_fri` VARCHAR(20) NULL DEFAULT NULL,
	`hirata_code_out_fri` INT(11) NULL DEFAULT NULL,
	`commuting_time_out_fri` VARCHAR(10) NULL DEFAULT NULL,
	`go_to_school_code_out_sat` INT(11) NULL DEFAULT NULL,
	`bus_course_id_out_sat` INT(11) NULL DEFAULT NULL,
	`bus_station_out_sat` VARCHAR(20) NULL DEFAULT NULL,
	`train_station_out_sat` VARCHAR(20) NULL DEFAULT NULL,
	`hirata_code_out_sat` INT(11) NULL DEFAULT NULL,
	`commuting_time_out_sat` VARCHAR(10) NULL DEFAULT NULL,
	`go_to_school_code_in_mon` INT(11) NULL DEFAULT NULL,
	`bus_course_id_in_mon` INT(11) NULL DEFAULT NULL,
	`bus_station_in_mon` VARCHAR(20) NULL DEFAULT NULL,
	`train_station_in_mon` VARCHAR(20) NULL DEFAULT NULL,
	`hirata_code_in_mon` INT(11) NULL DEFAULT NULL,
	`commuting_time_in_mon` VARCHAR(10) NULL DEFAULT NULL,
	`go_to_school_code_in_tue` INT(11) NULL DEFAULT NULL,
	`bus_course_id_in_tue` INT(11) NULL DEFAULT NULL,
	`bus_station_in_tue` VARCHAR(20) NULL DEFAULT NULL,
	`train_station_in_tue` VARCHAR(20) NULL DEFAULT NULL,
	`hirata_code_in_tue` INT(11) NULL DEFAULT NULL,
	`commuting_time_in_tue` VARCHAR(10) NULL DEFAULT NULL,
	`go_to_school_code_in_wed` INT(11) NULL DEFAULT NULL,
	`bus_course_id_in_wed` INT(11) NULL DEFAULT NULL,
	`bus_station_in_wed` VARCHAR(20) NULL DEFAULT NULL,
	`train_station_in_wed` VARCHAR(20) NULL DEFAULT NULL,
	`hirata_code_in_wed` INT(11) NULL DEFAULT NULL,
	`commuting_time_in_wed` VARCHAR(10) NULL DEFAULT NULL,
	`go_to_school_code_in_thu` INT(11) NULL DEFAULT NULL,
	`bus_course_id_in_thu` INT(11) NULL DEFAULT NULL,
	`bus_station_in_thu` VARCHAR(20) NULL DEFAULT NULL,
	`train_station_in_thu` VARCHAR(20) NULL DEFAULT NULL,
	`hirata_code_in_thu` INT(11) NULL DEFAULT NULL,
	`commuting_time_in_thu` VARCHAR(10) NULL DEFAULT NULL,
	`go_to_school_code_in_fri` INT(11) NULL DEFAULT NULL,
	`bus_course_id_in_fri` INT(11) NULL DEFAULT NULL,
	`bus_station_in_fri` VARCHAR(20) NULL DEFAULT NULL,
	`train_station_in_fri` VARCHAR(20) NULL DEFAULT NULL,
	`hirata_code_in_fri` INT(11) NULL DEFAULT NULL,
	`commuting_time_in_fri` VARCHAR(10) NULL DEFAULT NULL,
	`go_to_school_code_in_sat` INT(11) NULL DEFAULT NULL,
	`bus_course_id_in_sat` INT(11) NULL DEFAULT NULL,
	`bus_station_in_sat` VARCHAR(20) NULL DEFAULT NULL,
	`train_station_in_sat` VARCHAR(20) NULL DEFAULT NULL,
	`hirata_code_in_sat` INT(11) NULL DEFAULT NULL,
	`commuting_time_in_sat` VARCHAR(10) NULL DEFAULT NULL,
	`pre_school` VARCHAR(30) NULL DEFAULT NULL,
	`e_school_move_in` VARCHAR(30) NULL DEFAULT NULL,
	`e_school_move_in_date` CHAR(10) NULL DEFAULT NULL,
	`e_school_move_out` VARCHAR(30) NULL DEFAULT NULL,
	`e_school_move_out_date` CHAR(10) NULL DEFAULT NULL,
	`e_school_graduation` VARCHAR(30) NULL DEFAULT NULL,
	`e_school_graduation_date` CHAR(10) NULL DEFAULT NULL,
	`j_school_move_in` VARCHAR(30) NULL DEFAULT NULL,
	`j_school_move_in_date` CHAR(10) NULL DEFAULT NULL,
	`j_school_move_out` VARCHAR(30) NULL DEFAULT NULL,
	`j_school_move_out_date` CHAR(10) NULL DEFAULT NULL,
	`j_school_graduation` VARCHAR(30) NULL DEFAULT NULL,
	`j_school_graduation_date` CHAR(10) NULL DEFAULT NULL,
	`course_high_school` VARCHAR(20) NULL DEFAULT NULL,
	`course_proceed_to_school` VARCHAR(20) NULL DEFAULT NULL,
	`course_place_on_employment` VARCHAR(20) NULL DEFAULT NULL,
	`personal_contacts` VARCHAR(50) NULL DEFAULT NULL,
	`new_address` VARCHAR(50) NULL DEFAULT NULL,
	`create_id` INT(11) NOT NULL,
	`create_date` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
	`update_id` INT(11) NOT NULL,
	`update_date` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
	PRIMARY KEY (`pupil_id`),
	UNIQUE INDEX `pupil_card_num` (`pupil_card_num`),
	INDEX `sex_code` (`sex_code`),
	INDEX `family_relationship_code` (`family_relationship_code`),
	INDEX `district_id` (`district_id`),
	INDEX `go_to_school_code_out` (`go_to_school_code_out`),
	INDEX `bus_course_id_out` (`bus_course_id_out`),
	INDEX `go_to_school_code_in` (`go_to_school_code_in`),
	INDEX `bus_course_id_in` (`bus_course_id_in`),
	INDEX `ent_exam_id` (`ent_exam_id`),
	INDEX `emergency_contact_code1` (`emergency_contact1_kind_code`),
	INDEX `emergency_contact_code2` (`emergency_contact2_kind_code`),
	INDEX `emergency_contact_code3` (`emergency_contact3_kind_code`),
	INDEX `family_relationship_code1` (`family_structure1_relationship_code`),
	INDEX `family_relationship_code2` (`family_structure2_relationship_code`),
	INDEX `family_relationship_code3` (`family_structure3_relationship_code`),
	INDEX `family_relationship_code4` (`family_structure4_relationship_code`),
	INDEX `family_relationship_code5` (`family_structure5_relationship_code`),
	INDEX `family_relationship_code6` (`family_structure6_relationship_code`),
	INDEX `family_relationship_code7` (`family_structure7_relationship_code`),
	INDEX `family_relationship_code8` (`family_structure8_relationship_code`),
	INDEX `go_to_school_code_out1` (`go_to_school_code_out_mon`),
	INDEX `bus_course_id_out1` (`bus_course_id_out_mon`),
	INDEX `go_to_school_code_out2` (`go_to_school_code_out_tue`),
	INDEX `bus_course_id_out2` (`bus_course_id_out_tue`),
	INDEX `go_to_school_code_out3` (`go_to_school_code_out_wed`),
	INDEX `bus_course_id_out3` (`bus_course_id_out_wed`),
	INDEX `go_to_school_code_out4` (`go_to_school_code_out_thu`),
	INDEX `bus_course_id_out4` (`bus_course_id_out_thu`),
	INDEX `go_to_school_code_out5` (`go_to_school_code_out_fri`),
	INDEX `bus_course_id_out5` (`bus_course_id_out_fri`),
	INDEX `go_to_school_code_out6` (`go_to_school_code_out_sat`),
	INDEX `bus_course_id_out6` (`bus_course_id_out_sat`),
	INDEX `go_to_school_code_in1` (`go_to_school_code_in_mon`),
	INDEX `bus_course_id_in1` (`bus_course_id_in_mon`),
	INDEX `go_to_school_code_in2` (`go_to_school_code_in_tue`),
	INDEX `bus_course_id_in2` (`bus_course_id_in_tue`),
	INDEX `go_to_school_code_in3` (`go_to_school_code_in_wed`),
	INDEX `bus_course_id_in3` (`bus_course_id_in_wed`),
	INDEX `go_to_school_code_in4` (`go_to_school_code_in_thu`),
	INDEX `bus_course_id_in4` (`bus_course_id_in_thu`),
	INDEX `go_to_school_code_in5` (`go_to_school_code_in_fri`),
	INDEX `bus_course_id_in5` (`bus_course_id_in_fri`),
	INDEX `go_to_school_code_in6` (`go_to_school_code_in_sat`),
	INDEX `bus_course_id_in6` (`bus_course_id_in_sat`),
	INDEX `t_pupils_basic_ibfk_44` (`hirata_code_out_mon`),
	INDEX `t_pupils_basic_ibfk_45` (`hirata_code_out_tue`),
	INDEX `t_pupils_basic_ibfk_46` (`hirata_code_out_wed`),
	INDEX `t_pupils_basic_ibfk_47` (`hirata_code_out_thu`),
	INDEX `t_pupils_basic_ibfk_48` (`hirata_code_out_fri`),
	INDEX `t_pupils_basic_ibfk_49` (`hirata_code_out_sat`),
	INDEX `t_pupils_basic_ibfk_50` (`hirata_code_in_mon`),
	INDEX `t_pupils_basic_ibfk_51` (`hirata_code_in_tue`),
	INDEX `t_pupils_basic_ibfk_52` (`hirata_code_in_wed`),
	INDEX `t_pupils_basic_ibfk_53` (`hirata_code_in_thu`),
	INDEX `t_pupils_basic_ibfk_54` (`hirata_code_in_fri`),
	INDEX `t_pupils_basic_ibfk_55` (`hirata_code_in_sat`),
	CONSTRAINT `t_pupils_basic_ibfk_1` FOREIGN KEY (`sex_code`) REFERENCES `m_sex_code` (`sex_code`),
	CONSTRAINT `t_pupils_basic_ibfk_10` FOREIGN KEY (`emergency_contact2_kind_code`) REFERENCES `m_emergency_contact_code` (`emergency_contact_code`),
	CONSTRAINT `t_pupils_basic_ibfk_11` FOREIGN KEY (`emergency_contact3_kind_code`) REFERENCES `m_emergency_contact_code` (`emergency_contact_code`),
	CONSTRAINT `t_pupils_basic_ibfk_12` FOREIGN KEY (`family_structure1_relationship_code`) REFERENCES `m_family_relationship_code` (`family_relationship_code`),
	CONSTRAINT `t_pupils_basic_ibfk_13` FOREIGN KEY (`family_structure2_relationship_code`) REFERENCES `m_family_relationship_code` (`family_relationship_code`),
	CONSTRAINT `t_pupils_basic_ibfk_14` FOREIGN KEY (`family_structure3_relationship_code`) REFERENCES `m_family_relationship_code` (`family_relationship_code`),
	CONSTRAINT `t_pupils_basic_ibfk_15` FOREIGN KEY (`family_structure4_relationship_code`) REFERENCES `m_family_relationship_code` (`family_relationship_code`),
	CONSTRAINT `t_pupils_basic_ibfk_16` FOREIGN KEY (`family_structure5_relationship_code`) REFERENCES `m_family_relationship_code` (`family_relationship_code`),
	CONSTRAINT `t_pupils_basic_ibfk_17` FOREIGN KEY (`family_structure6_relationship_code`) REFERENCES `m_family_relationship_code` (`family_relationship_code`),
	CONSTRAINT `t_pupils_basic_ibfk_18` FOREIGN KEY (`family_structure7_relationship_code`) REFERENCES `m_family_relationship_code` (`family_relationship_code`),
	CONSTRAINT `t_pupils_basic_ibfk_19` FOREIGN KEY (`family_structure8_relationship_code`) REFERENCES `m_family_relationship_code` (`family_relationship_code`),
	CONSTRAINT `t_pupils_basic_ibfk_2` FOREIGN KEY (`family_relationship_code`) REFERENCES `m_family_relationship_code` (`family_relationship_code`),
	CONSTRAINT `t_pupils_basic_ibfk_20` FOREIGN KEY (`go_to_school_code_out_mon`) REFERENCES `m_go_to_school_code` (`go_to_school_code`),
	CONSTRAINT `t_pupils_basic_ibfk_21` FOREIGN KEY (`bus_course_id_out_mon`) REFERENCES `m_bus_course` (`bus_course_id`),
	CONSTRAINT `t_pupils_basic_ibfk_22` FOREIGN KEY (`go_to_school_code_out_tue`) REFERENCES `m_go_to_school_code` (`go_to_school_code`),
	CONSTRAINT `t_pupils_basic_ibfk_23` FOREIGN KEY (`bus_course_id_out_tue`) REFERENCES `m_bus_course` (`bus_course_id`),
	CONSTRAINT `t_pupils_basic_ibfk_24` FOREIGN KEY (`go_to_school_code_out_wed`) REFERENCES `m_go_to_school_code` (`go_to_school_code`),
	CONSTRAINT `t_pupils_basic_ibfk_25` FOREIGN KEY (`bus_course_id_out_wed`) REFERENCES `m_bus_course` (`bus_course_id`),
	CONSTRAINT `t_pupils_basic_ibfk_26` FOREIGN KEY (`go_to_school_code_out_thu`) REFERENCES `m_go_to_school_code` (`go_to_school_code`),
	CONSTRAINT `t_pupils_basic_ibfk_27` FOREIGN KEY (`bus_course_id_out_thu`) REFERENCES `m_bus_course` (`bus_course_id`),
	CONSTRAINT `t_pupils_basic_ibfk_28` FOREIGN KEY (`go_to_school_code_out_fri`) REFERENCES `m_go_to_school_code` (`go_to_school_code`),
	CONSTRAINT `t_pupils_basic_ibfk_29` FOREIGN KEY (`bus_course_id_out_fri`) REFERENCES `m_bus_course` (`bus_course_id`),
	CONSTRAINT `t_pupils_basic_ibfk_3` FOREIGN KEY (`district_id`) REFERENCES `m_district` (`district_id`),
	CONSTRAINT `t_pupils_basic_ibfk_30` FOREIGN KEY (`go_to_school_code_out_sat`) REFERENCES `m_go_to_school_code` (`go_to_school_code`),
	CONSTRAINT `t_pupils_basic_ibfk_31` FOREIGN KEY (`bus_course_id_out_sat`) REFERENCES `m_bus_course` (`bus_course_id`),
	CONSTRAINT `t_pupils_basic_ibfk_32` FOREIGN KEY (`go_to_school_code_in_mon`) REFERENCES `m_go_to_school_code` (`go_to_school_code`),
	CONSTRAINT `t_pupils_basic_ibfk_33` FOREIGN KEY (`bus_course_id_in_mon`) REFERENCES `m_bus_course` (`bus_course_id`),
	CONSTRAINT `t_pupils_basic_ibfk_34` FOREIGN KEY (`go_to_school_code_in_tue`) REFERENCES `m_go_to_school_code` (`go_to_school_code`),
	CONSTRAINT `t_pupils_basic_ibfk_35` FOREIGN KEY (`bus_course_id_in_tue`) REFERENCES `m_bus_course` (`bus_course_id`),
	CONSTRAINT `t_pupils_basic_ibfk_36` FOREIGN KEY (`go_to_school_code_in_wed`) REFERENCES `m_go_to_school_code` (`go_to_school_code`),
	CONSTRAINT `t_pupils_basic_ibfk_37` FOREIGN KEY (`bus_course_id_in_wed`) REFERENCES `m_bus_course` (`bus_course_id`),
	CONSTRAINT `t_pupils_basic_ibfk_38` FOREIGN KEY (`go_to_school_code_in_thu`) REFERENCES `m_go_to_school_code` (`go_to_school_code`),
	CONSTRAINT `t_pupils_basic_ibfk_39` FOREIGN KEY (`bus_course_id_in_thu`) REFERENCES `m_bus_course` (`bus_course_id`),
	CONSTRAINT `t_pupils_basic_ibfk_4` FOREIGN KEY (`go_to_school_code_out`) REFERENCES `m_go_to_school_code` (`go_to_school_code`),
	CONSTRAINT `t_pupils_basic_ibfk_40` FOREIGN KEY (`go_to_school_code_in_fri`) REFERENCES `m_go_to_school_code` (`go_to_school_code`),
	CONSTRAINT `t_pupils_basic_ibfk_41` FOREIGN KEY (`bus_course_id_in_fri`) REFERENCES `m_bus_course` (`bus_course_id`),
	CONSTRAINT `t_pupils_basic_ibfk_42` FOREIGN KEY (`go_to_school_code_in_sat`) REFERENCES `m_go_to_school_code` (`go_to_school_code`),
	CONSTRAINT `t_pupils_basic_ibfk_43` FOREIGN KEY (`bus_course_id_in_sat`) REFERENCES `m_bus_course` (`bus_course_id`),
	CONSTRAINT `t_pupils_basic_ibfk_44` FOREIGN KEY (`hirata_code_out_mon`) REFERENCES `m_hirata_code` (`hirata_code`),
	CONSTRAINT `t_pupils_basic_ibfk_45` FOREIGN KEY (`hirata_code_out_tue`) REFERENCES `m_hirata_code` (`hirata_code`),
	CONSTRAINT `t_pupils_basic_ibfk_46` FOREIGN KEY (`hirata_code_out_wed`) REFERENCES `m_hirata_code` (`hirata_code`),
	CONSTRAINT `t_pupils_basic_ibfk_47` FOREIGN KEY (`hirata_code_out_thu`) REFERENCES `m_hirata_code` (`hirata_code`),
	CONSTRAINT `t_pupils_basic_ibfk_48` FOREIGN KEY (`hirata_code_out_fri`) REFERENCES `m_hirata_code` (`hirata_code`),
	CONSTRAINT `t_pupils_basic_ibfk_49` FOREIGN KEY (`hirata_code_out_sat`) REFERENCES `m_hirata_code` (`hirata_code`),
	CONSTRAINT `t_pupils_basic_ibfk_5` FOREIGN KEY (`bus_course_id_out`) REFERENCES `m_bus_course` (`bus_course_id`),
	CONSTRAINT `t_pupils_basic_ibfk_50` FOREIGN KEY (`hirata_code_in_mon`) REFERENCES `m_hirata_code` (`hirata_code`),
	CONSTRAINT `t_pupils_basic_ibfk_51` FOREIGN KEY (`hirata_code_in_tue`) REFERENCES `m_hirata_code` (`hirata_code`),
	CONSTRAINT `t_pupils_basic_ibfk_52` FOREIGN KEY (`hirata_code_in_wed`) REFERENCES `m_hirata_code` (`hirata_code`),
	CONSTRAINT `t_pupils_basic_ibfk_53` FOREIGN KEY (`hirata_code_in_thu`) REFERENCES `m_hirata_code` (`hirata_code`),
	CONSTRAINT `t_pupils_basic_ibfk_54` FOREIGN KEY (`hirata_code_in_fri`) REFERENCES `m_hirata_code` (`hirata_code`),
	CONSTRAINT `t_pupils_basic_ibfk_55` FOREIGN KEY (`hirata_code_in_sat`) REFERENCES `m_hirata_code` (`hirata_code`),
	CONSTRAINT `t_pupils_basic_ibfk_6` FOREIGN KEY (`go_to_school_code_in`) REFERENCES `m_go_to_school_code` (`go_to_school_code`),
	CONSTRAINT `t_pupils_basic_ibfk_7` FOREIGN KEY (`bus_course_id_in`) REFERENCES `m_bus_course` (`bus_course_id`),
	CONSTRAINT `t_pupils_basic_ibfk_8` FOREIGN KEY (`ent_exam_id`) REFERENCES `t_ent_exam` (`ent_exam_id`),
	CONSTRAINT `t_pupils_basic_ibfk_9` FOREIGN KEY (`emergency_contact1_kind_code`) REFERENCES `m_emergency_contact_code` (`emergency_contact_code`)
)
;
